<?php

return [
    'name' => 'Franchise',
    'description' => 'Config email templates for Franchise',
    'templates' => [
        'store_new_order' => [
            'title' => 'plugins/franchise::franchise.email.store_new_order_title',
            'description' => 'plugins/franchise::franchise.email.store_new_order_description',
            'subject' => 'plugins/franchise::franchise.email.store_new_order_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'product_list' => 'plugins/ecommerce::ecommerce.product_list',
                'shipping_method' => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method' => 'plugins/ecommerce::ecommerce.payment_method',
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone' => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'store' => 'plugins/franchise::franchise.email.store',
                'order' => 'plugins/franchise::franchise.email.order',
                'shipment' => 'plugins/franchise::franchise.email.shipment',
                'address' => 'plugins/franchise::franchise.email.address',
                'products' => 'plugins/franchise::franchise.email.products',
            ],
        ],
        'verify_vendor' => [
            'title' => 'plugins/franchise::franchise.email.verify_vendor_title',
            'description' => 'plugins/franchise::franchise.email.verify_vendor_description',
            'subject' => 'plugins/franchise::franchise.email.verify_vendor_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone' => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'store' => 'plugins/franchise::franchise.email.store',
            ],
        ],
        'vendor-account-approved' => [
            'title' => 'plugins/franchise::franchise.email.vendor_account_approved_title',
            'description' => 'plugins/franchise::franchise.email.vendor_account_approved_description',
            'subject' => 'plugins/franchise::franchise.email.vendor_account_approved_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'store' => 'plugins/franchise::franchise.email.store',
            ],
        ],
        'vendor-account-rejected' => [
            'title' => 'plugins/franchise::franchise.email.vendor_account_rejected_title',
            'description' => 'plugins/franchise::franchise.email.vendor_account_rejected_description',
            'subject' => 'plugins/franchise::franchise.email.vendor_account_rejected_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'store' => 'plugins/franchise::franchise.email.store',
            ],
        ],
        'pending-product-approval' => [
            'title' => 'plugins/franchise::franchise.email.pending_product_approval_title',
            'description' => 'plugins/franchise::franchise.email.pending_product_approval_description',
            'subject' => 'plugins/franchise::franchise.email.pending_product_approval_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'product_name' => 'plugins/franchise::franchise.product_name',
                'product_url' => 'plugins/franchise::franchise.product_url',
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'store' => 'plugins/franchise::franchise.email.store',
            ],
        ],
        'product-approved' => [
            'title' => 'plugins/franchise::franchise.email.product_approved_title',
            'description' => 'plugins/franchise::franchise.email.product_approved_description',
            'subject' => 'plugins/franchise::franchise.email.product_approved_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'store' => 'plugins/franchise::franchise.email.store',
            ],
        ],
        'withdrawal-approved' => [
            'title' => 'plugins/franchise::franchise.email.withdrawal_approved_title',
            'description' => 'plugins/franchise::franchise.email.withdrawal_approved_description',
            'subject' => 'plugins/franchise::franchise.email.withdrawal_approved_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'withdrawal_amount' => 'plugins/franchise::franchise.withdrawal_amount',
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'store' => 'plugins/franchise::franchise.email.store',
            ],
        ],
        'welcome-vendor' => [
            'title' => 'plugins/franchise::franchise.email.welcome_vendor_title',
            'description' => 'plugins/franchise::franchise.email.welcome_vendor_description',
            'subject' => 'plugins/franchise::franchise.email.welcome_vendor_subject',
            'can_off' => true,
            'enabled' => false,
            'variables' => [
                'vendor_name' => 'plugins/franchise::franchise.vendor_name',
                'store_name' => 'plugins/franchise::franchise.store_name',
            ],
        ],
        'contact-store' => [
            'title' => 'plugins/franchise::franchise.email.contact_store_title',
            'description' => 'plugins/franchise::franchise.email.contact_store_description',
            'subject' => 'plugins/franchise::franchise.email.contact_store_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'store_name' => 'plugins/franchise::franchise.store_name',
                'store_phone' => 'plugins/franchise::franchise.store_phone',
                'store_address' => 'plugins/franchise::franchise.store_address',
                'store_url' => 'plugins/franchise::franchise.store_url',
                'customer_message' => 'plugins/franchise::franchise.email.customer_message',
                'customer_name' => 'plugins/franchise::franchise.email.customer_name',
                'customer_email' => 'plugins/franchise::franchise.email.customer_email',
            ],
        ],
        'vendor-account-blocked' => [
            'title' => 'plugins/franchise::franchise.email.vendor_account_blocked_title',
            'description' => 'plugins/franchise::franchise.email.vendor_account_blocked_description',
            'subject' => 'plugins/franchise::franchise.email.vendor_account_blocked_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'block_reason' => 'plugins/franchise::franchise.email.block_reason',
                'block_date' => 'plugins/franchise::franchise.email.block_date',
            ],
        ],
        'vendor-account-unblocked' => [
            'title' => 'plugins/franchise::franchise.email.vendor_account_unblocked_title',
            'description' => 'plugins/franchise::franchise.email.vendor_account_unblocked_description',
            'subject' => 'plugins/franchise::franchise.email.vendor_account_unblocked_subject',
            'can_off' => true,
            'enabled' => true,
            'variables' => [
                'unblock_date' => 'plugins/franchise::franchise.email.unblock_date',
            ],
        ],
    ],
];
