<?php

namespace Botble\Course\Facades;

use Botble\Course\Supports\CourseHelper as BaseCourseHelper;
use Illuminate\Support\Facades\Facade;

/**
 * @method static bool isCartEnabled()
 * @method static bool isWishlistEnabled()
 * @method static bool isCompareEnabled()
 * @method static bool isCourseInCompare(string|int $courseId)
 * @method static bool isReviewEnabled()
 * @method static bool isOrderTrackingEnabled()
 * @method static bool isOrderAutoConfirmedEnabled()
 * @method static float reviewMaxFileSize(bool $isConvertToKB = false)
 * @method static int reviewMaxFileNumber()
 * @method static \Illuminate\Support\Collection getReviewsGroupedByCourseId(string|int $courseId, int $reviewsCount = 0)
 * @method static bool isQuickBuyButtonEnabled()
 * @method static string getQuickBuyButtonTarget()
 * @method static bool isZipCodeEnabled()
 * @method static bool isBillingAddressEnabled()
 * @method static bool isDisplayCourseIncludingTaxes()
 * @method static bool isTaxEnabled()
 * @method static array getAvailableCountries()
 * @method static array getAvailableStatesByCountry(string|int|null $countryId)
 * @method static array getAvailableCitiesByState(string|int|null $stateId, string|int|null $countryId = null)
 * @method static array getSortParams()
 * @method static array getShowParams()
 * @method static float getMinimumOrderAmount()
 * @method static bool isEnabledGuestCheckout()
 * @method static bool showNumberOfCoursesInCourseSingle()
 * @method static bool showOutOfStockCourses()
 * @method static array getDateRangeInReport(\Illuminate\Http\Request $request)
 * @method static string|null getSettingPrefix()
 * @method static bool isEnableEmailVerification()
 * @method static bool disableOrderInvoiceUntilOrderConfirmed()
 * @method static bool isEnabledCourseOptions()
 * @method static bool isEnabledCrossSaleCourses()
 * @method static bool isEnabledRelatedCourses()
 * @method static string getPhoneValidationRule()
 * @method static \Illuminate\Pagination\LengthAwarePaginator getCourseReviews(\Botble\Course\Models\Course $course, int $star = 0, int $perPage = 10)
 * @method static string getThousandSeparatorForInputMask()
 * @method static string getDecimalSeparatorForInputMask()
 * @method static array withReviewsParams()
 * @method static bool loadCountriesStatesCitiesFromPluginLocation()
 * @method static string|null getCountryNameById(string|int|null $countryId)
 * @method static array getStates(string|null $countryCode)
 * @method static array getCities(string|int|null $stateId)
 * @method static bool isUsingInMultipleCountries()
 * @method static string|int getFirstCountryId()
 * @method static array getCustomerAddressValidationRules(string|null $prefix = '')
 * @method static bool isEnabledCustomerRecentlyViewedCourses()
 * @method static int maxCustomerRecentlyViewedCourses()
 * @method static \Botble\Course\Supports\CourseHelper handleCustomerRecentlyViewedCourse(\Botble\Course\Models\Course $course)
 * @method static array getCourseVariationInfo(\Botble\Course\Models\Course $course, array $params = [])
 * @method static array getCoursesSearchBy()
 * @method static int|float validateOrderWeight(int|float $weight)
 * @method static bool isFacebookPixelEnabled()
 * @method static int getReturnableDays()
 * @method static bool canCustomReturnCourseQty()
 * @method static bool isOrderReturnEnabled()
 * @method static bool allowPartialReturn()
 * @method static bool isAvailableShipping(\Illuminate\Support\Collection $courses)
 * @method static int countDigitalCourses(\Illuminate\Support\Collection $courses)
 * @method static bool canCheckoutForDigitalCourses(\Illuminate\Support\Collection $courses)
 * @method static bool isEnabledSupportDigitalCourses()
 * @method static bool allowGuestCheckoutForDigitalCourses()
 * @method static bool isSaveOrderShippingAddress(\Illuminate\Support\Collection $courses)
 * @method static bool courseFilterParamsValidated(\Illuminate\Http\Request $request)
 * @method static string viewPath(string $view)
 * @method static array getOriginAddress()
 * @method static array getShippingData(\Illuminate\Support\Collection|array $courses, array $session, array $origin, float $orderTotal, string|null $paymentMethod = null)
 * @method static bool onlyAllowCustomersPurchasedToReview()
 * @method static bool isValidToProcessCheckout()
 * @method static array getMandatoryFieldsAtCheckout()
 * @method static array getEnabledMandatoryFieldsAtCheckout()
 * @method static array getHiddenFieldsAtCheckout()
 * @method static array withCourseEagerLoadingRelations()
 * @method static bool isDisplayTaxFieldsAtCheckoutPage()
 * @method static int getCourseMaxPrice(array $categoryIds = [])
 * @method static void clearCourseMaxPriceCache()
 * @method static bool isEnabledFilterCoursesByBrands()
 * @method static bool isEnabledFilterCoursesByTags()
 * @method static bool isEnabledFilterCoursesByAttributes()
 * @method static \Illuminate\Support\Collection brandsForFilter(array $categoryIds = [])
 * @method static \Illuminate\Support\Collection tagsForFilter(array $categoryIds = [])
 * @method static array dataForFilter(\Botble\Course\Models\CourseCategory|null $category)
 * @method static array dataPriceRangesForFilter()
 * @method static bool isPriceRangesChecked(float $fromPrice, float $toPrice)
 * @method static array dataPriceRanges(int $stepPrice = 1000, int $stepCount = 10)
 * @method static bool useCityFieldAsTextField()
 * @method static bool isLoginUsingPhone()
 * @method static string getLoginOption()
 * @method static void registerThemeAssets()
 * @method static array|string|null getDefaultPageSlug(string|null $key = null)
 * @method static string|null getPageSlug(string $key)
 * @method static string jsAttributes(string $action, \Botble\Course\Models\Course $course, array $additional = [])
 * @method static string getAdminPrefix()
 * @method static \Illuminate\Routing\RouteRegistrar registerRoutes(\Closure|callable $closure, array $middleware = [])
 * @method static \Illuminate\Routing\RouteRegistrar registerFallbackRoutes(string $prefix)
 * @method static int getMinimumOrderQuantity()
 * @method static int getMaximumOrderQuantity()
 * @method static string|null getWishlistCode()
 * @method static bool isWishlistSharingEnabled()
 * @method static int getSharedWishlistLifetime()
 * @method static bool isDisabledPhysicalCourse()
 * @method static string|null getCurrentCreationContextCourseType()
 * @method static void registerCourseVideo()
 * @method static void registerCourseGalleryOptions()
 * @method static bool isCourseSpecificationEnabled()
 *
 * @see \Botble\Course\Supports\CourseHelper
 */
class CourseHelper extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return BaseCourseHelper::class;
    }
}
